/*
 Generated by typeshare 1.13.3
*/

export interface CodeNodeData {
	code: string;
	inputs?: any;
}

export interface ExecutionResult {
	node_id: string;
	status_code: number;
	body: any;
	timestamp: number;
}

export enum HttpMethod {
	GET = "GET",
	POST = "POST",
	PUT = "PUT",
	DELETE = "DELETE",
	PATCH = "PATCH",
}

export interface HttpNodeData {
	url: string;
	method: HttpMethod;
	headers?: Record<string, string>;
	body?: any;
}

export type NodeType = 
	| { type: "HTTP", data: HttpNodeData }
	| { type: "CODE", data: CodeNodeData };

export interface WorkerJob {
	id: string;
	node: NodeType;
}

