/*
 Generated by typeshare 1.13.3
*/

export interface CodeNodeData {
	code: string;
	inputs?: any;
}

export interface DelayNodeData {
	duration_ms: number;
	duration_str?: string;
}

export interface DelayResumeData {
	original_delay_ms: number;
}

export interface ExecutionResult {
	node_id: string;
	run_id?: string;
	status_code: number;
	body: any;
	timestamp: number;
	duration_ms: number;
}

export enum HttpMethod {
	GET = "GET",
	POST = "POST",
	PUT = "PUT",
	DELETE = "DELETE",
	PATCH = "PATCH",
}

export interface HttpNodeData {
	url: string;
	method: HttpMethod;
	headers?: Record<string, string>;
	body?: any;
}

export interface WebhookResumeData {
	resume_token: string;
	payload: any;
}

export interface WebhookWaitData {
	description?: string;
	timeout_ms: number;
}

export type NodeType = 
	| { type: "HTTP", data: HttpNodeData }
	| { type: "CODE", data: CodeNodeData }
	| { type: "DELAY", data: DelayNodeData }
	| { type: "DELAYRESUME", data: DelayResumeData }
	| { type: "WEBHOOKWAIT", data: WebhookWaitData }
	| { type: "WEBHOOKRESUME", data: WebhookResumeData };

export interface WorkerJob {
	id: string;
	run_id?: string;
	node: NodeType;
	retry_count?: number;
	max_retries: number;
}

