/*
 Generated by typeshare 1.13.3
*/

export interface ExecutionResult {
	node_id: string;
	status_code: number;
	body: any;
	timestamp: number;
}

export enum HttpMethod {
	GET = "GET",
	POST = "POST",
	PUT = "PUT",
	DELETE = "DELETE",
	PATCH = "PATCH",
}

export interface HttpRequestNode {
	id: string;
	url: string;
	method: HttpMethod;
	headers?: Record<string, string>;
	body?: any;
}

