// Re-export all worker types (generated by typeshare)
export * from './worker';

// Shared constants
export const APP_NAME = 'SwiftGrid';

// Redis stream names
export const REDIS_STREAMS = {
    JOBS: 'swiftgrid_stream',
    RESULTS: 'swiftgrid_results'
} as const;

