/*
 Generated by typeshare 1.13.3
*/

export interface CodeNodeData {
	code: string;
	inputs?: any;
}

export interface DelayNodeData {
	/** Delay duration in milliseconds */
	duration_ms: number;
	/** Human-readable duration string: "5s", "2m", "1h" */
	duration_str?: string;
}

export interface DelayResumeData {
	original_delay_ms: number;
}

export interface ExecutionResult {
	node_id: string;
	run_id?: string;
	status_code: number;
	body: any;
	timestamp: number;
	duration_ms: number;
	/** If true, frontend should not trigger downstream */
	isolated?: boolean;
}

export enum HttpMethod {
	GET = "GET",
	POST = "POST",
	PUT = "PUT",
	DELETE = "DELETE",
	PATCH = "PATCH",
}

export interface HttpNodeData {
	url: string;
	method: HttpMethod;
	headers?: Record<string, string>;
	body?: any;
}

export interface LlmMessage {
	/** "system", "user", or "assistant" */
	role: string;
	content: string;
}

export interface LlmNodeData {
	/** Base URL: "https://api.openai.com/v1" or custom */
	base_url: string;
	/** API key (can be {{$env.OPENAI_KEY}}) */
	api_key: string;
	/** Model name: "gpt-4o", "gpt-3.5-turbo", etc. */
	model: string;
	/** Conversation messages */
	messages: LlmMessage[];
	/** Temperature: 0.0 - 2.0 */
	temperature?: number;
	/** Max response tokens */
	max_tokens?: number;
	/** Enable streaming (default: false) */
	stream?: boolean;
}

export interface RouterCondition {
	/** Output handle ID */
	id: string;
	/** Display label (e.g., "Success", "Error") */
	label: string;
	/** JS expression: "value >= 200 && value < 300" */
	expression: string;
}

export interface RouterNodeData {
	/** Variable to evaluate: "{{node.status}}" */
	route_by: string;
	/** Conditions to check in order */
	conditions: RouterCondition[];
	/** Output if no conditions match */
	default_output: string;
	/** "first_match" or "broadcast" */
	mode: string;
}

export interface WebhookResumeData {
	resume_token: string;
	payload: any;
}

export interface WebhookWaitData {
	/** Description shown to user: "Wait for payment confirmation" */
	description?: string;
	/** Timeout in milliseconds (default: 7 days) */
	timeout_ms: number;
}

export type NodeType = 
	| { type: "HTTP", data: HttpNodeData }
	| { type: "CODE", data: CodeNodeData }
	| { type: "DELAY", data: DelayNodeData }
	| { type: "DELAYRESUME", data: DelayResumeData }
	| { type: "WEBHOOKWAIT", data: WebhookWaitData }
	| { type: "WEBHOOKRESUME", data: WebhookResumeData }
	| { type: "ROUTER", data: RouterNodeData }
	| { type: "LLM", data: LlmNodeData };

export interface WorkerJob {
	/** Node ID */
	id: string;
	/** Run UUID (optional for backwards compat) */
	run_id?: string;
	/** The node to execute */
	node: NodeType;
	/** Current retry attempt (0-indexed) */
	retry_count?: number;
	/** Maximum retry attempts */
	max_retries: number;
	/** If true, don't trigger downstream nodes */
	isolated?: boolean;
}

